>P1;2wv7A
structureX:2wv7A:1: : 298  : :  : : -1.00 :-1.00
---KFRLIPYKQVDKVSALSEVPMGVEIVEAPAVWRASAKGAGQIIGVIDTGCQVDHPDL
AERIIGGVNLTTDYGGDETNFSDNNGHGTHVAGTVAAAETG-SGVVGVAPKADLFIIKAL
S-GD------GSGEMGWIAKAIRYAVDWRGPKGEQMRIITMSLGGPTDSEELHDAVKYAV
SNNVSVVCAAGNN----------EFAYPAAYNEVIAVGAVDFDLR----LE----IDIVA
PGVGIKSTYLDSGYAELSGTAMAAPHVAGALALIINLAEDAFKRSLSETEIYAQLVRRAT
PIGFTAQAEGNGFLTLDLVERITGQFT--------*
>P1;6f9mA
structureX:6f9mA:1: : 293  : :  : : -1.00 :-1.00
---NIHLIPYRVEQVTAAPPRIPEGVRMIQAPELWESAEHGKGNVVAVLDTGCQTDHPDL
TARIAGGRNFTHDDGGDPERFEDYNGHGTHVAGTVAASLRDEEGVVGVAPLADLLVVKVL
D-KE------GSGSYEGIIAGIHYAIDWRGPEGQKTTVISMSLGGPEDHPELYEAVKRAV
DAGIPVICAA-GT---------DEFAYPGAYGEVIQVGAVDFDRR----IN---EIDLVA
PGINIYSTYLEGKYASLSGTSMATPHVSGALALIRNISEREFDRELTEAELYAQLVRRTI
PLGYPKTAEGNGLLALDIL-----N----------*
>P1;7xr8A
structureX:7xr8A:1: : 292  : :  : : -1.00 :-1.00
---TIRLIPFKIEEKLESVKEIPEGVNMVQAPEIWKEGIRGKDIVIAVIDTGCDRDHPDL
KDRIIGGRNFTTDDNGDVDNYSDYNGHGTHVAGTIAATEND-QGVVGVAPEAKLLILKVL
A-NDPNNPGSATGKYEWIVNAINYAIDQ------KVDIISMSLGGPSDVPELHQAVKRAV
ENNILVVCAA-GE-----------LSYPAAYNEVISVGAISLDGQ----IE----IDVVA
PGEKILSTIPGGKFAVFSGTSMATPHVSGALALIKQLSEKEFERNLTEPELYAQLIKRTM
PLGFPKALEGNGLVYLTAPNLLS------------*
>P1;7y6mC
structureX:7y6mC:1: : 290  : :  : : -1.00 :-1.00
-------------------KETPESIQEIKAPELWSSGFKGKGITIAVLDTGCDTEHPDL
KDQIIGGKNFTDDDDGDAENVKDYNGHGTHVAGTIAATDQ-NGGILGVAPEAKLLIVKVL
GGEN------GSGKYEWIIDGINYAAEQ------KVDIISMSLGGPSNEPALQEAIQNAV
KSGVLVVCAAGNEGDGDERTEEF--SYPAAYNEVIAVGSVSLARESSEFSNANKEIDLVA
PGEDILSTLPNHKYGRLTGTSMAAPHVSGALAIIKNAEEEAFQRKLTEPEIYAQLVRRTL
PLKQSKALVGNGFLYLTAPDVLL-E----------*
>P1;P11018
structureX:P11018:1: : 319  : :  : : -1.00 :-1.00
MNGEIRLIPYVTNEQIMDVNELPEGIKVIKAPEMWAKGVKGKNIKVAVLDTGCDTSHPDL
KNQIIGGKNFTDDDGGKEDAISDYNGHGTHVAGTIAANDS-NGGIAGVAPEASLLIVKVL
GGEN------GSGQYEWIINGINYAVEQ------KVDIISMSLGGPSDVPELKEAVKNAV
KNGVLVVCAAGNEGDGDERTEEL--SYPAAYNEVIAVGSVSVARELSEFSNANKEIDLVA
PGENILSTLPNKKYGKLTGTSMAAPHVSGALALIKSYEEESFQRKLSESEVFAQLIRRTL
PLDIAKTLAGNGFLYLTAPDELA-EKAEQSHLLTL*
